-- =====================================================================
-- SUPABASE POSTGRESQL SCHEMA FOR EDX-STYLE LEARNING APPLICATION
-- =====================================================================

-- Enable UUID extension if not enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Clean up existing objects if rewriting (for testing/resetting)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP TRIGGER IF EXISTS on_enrollment_completed ON public.enrollments;
DROP FUNCTION IF EXISTS public.generate_certificate_on_completion();
DROP TRIGGER IF EXISTS on_enrollment_changed ON public.enrollments;
DROP FUNCTION IF EXISTS public.update_course_enrollment_count();

DROP TABLE IF EXISTS public.certificates CASCADE;
DROP TABLE IF EXISTS public.quiz_attempts CASCADE;
DROP TABLE IF EXISTS public.quizzes CASCADE;
DROP TABLE IF EXISTS public.enrollments CASCADE;
DROP TABLE IF EXISTS public.lessons CASCADE;
DROP TABLE IF EXISTS public.courses CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- =====================================================================
-- 1. TABLE CREATION
-- =====================================================================

-- Users Profile Table (linked to Supabase auth.users)
CREATE TABLE public.users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL UNIQUE,
    full_name TEXT,
    avatar_url TEXT,
    role TEXT DEFAULT 'student' CHECK (role IN ('student', 'instructor', 'admin')),
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Course Categories Table
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    icon TEXT,
    color TEXT
);

-- Courses Table
CREATE TABLE public.courses (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    thumbnail TEXT,
    instructor_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    price DECIMAL(10, 2) DEFAULT 0.00 NOT NULL CHECK (price >= 0),
    level TEXT DEFAULT 'beginner' CHECK (level IN ('beginner', 'intermediate', 'advanced')),
    duration INT DEFAULT 0 NOT NULL CHECK (duration >= 0), -- total duration in minutes
    rating DECIMAL(3, 2) DEFAULT 0.00 CHECK (rating BETWEEN 0.00 AND 5.00),
    enrolled_count INT DEFAULT 0 NOT NULL CHECK (enrolled_count >= 0)
);

-- Lessons Table
CREATE TABLE public.lessons (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    course_id UUID REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    video_url TEXT,
    content TEXT,
    order_index INT NOT NULL CHECK (order_index >= 0),
    duration INT DEFAULT 0 NOT NULL CHECK (duration >= 0), -- duration in minutes
    CONSTRAINT unique_course_lesson_order UNIQUE (course_id, order_index)
);

-- Course Enrollments Table (Many-to-Many relation between Users and Courses)
CREATE TABLE public.enrollments (
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    course_id UUID REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
    enrolled_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    progress_percent INT DEFAULT 0 NOT NULL CHECK (progress_percent BETWEEN 0 AND 100),
    completed_at TIMESTAMPTZ,
    PRIMARY KEY (user_id, course_id)
);

-- Quizzes Table
CREATE TABLE public.quizzes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    lesson_id UUID REFERENCES public.lessons(id) ON DELETE CASCADE NOT NULL,
    question TEXT NOT NULL,
    options JSONB NOT NULL, -- Format: ["Option A", "Option B", "Option C", "Option D"]
    correct_answer TEXT NOT NULL,
    explanation TEXT
);

-- Quiz Attempts Table
CREATE TABLE public.quiz_attempts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    quiz_id UUID REFERENCES public.quizzes(id) ON DELETE CASCADE NOT NULL,
    selected_answer TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL,
    attempted_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Certificates Table
CREATE TABLE public.certificates (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    course_id UUID REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
    issued_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    certificate_url TEXT NOT NULL,
    CONSTRAINT unique_user_course_certificate UNIQUE (user_id, course_id)
);

-- =====================================================================
-- 2. DATABASE TRIGGERS & AUTOMATION
-- =====================================================================

-- Trigger: Automatically sync newly created Supabase Auth users to public.users profiles
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, email, full_name, avatar_url, role)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', 'Học viên mới'),
    COALESCE(NEW.raw_user_meta_data->>'avatar_url', ''),
    COALESCE(NEW.raw_user_meta_data->>'role', 'student')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- Trigger: Increment or decrement courses.enrolled_count automatically on enrollments change
CREATE OR REPLACE FUNCTION public.update_course_enrollment_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.courses
    SET enrolled_count = enrolled_count + 1
    WHERE id = NEW.course_id;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE public.courses
    SET enrolled_count = GREATEST(0, enrolled_count - 1)
    WHERE id = OLD.course_id;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_enrollment_changed
  AFTER INSERT OR DELETE ON public.enrollments
  FOR EACH ROW EXECUTE FUNCTION public.update_course_enrollment_count();


-- Trigger: Auto-generate certificate and set completed_at timestamp when progress_percent hits 100%
CREATE OR REPLACE FUNCTION public.generate_certificate_on_completion()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.progress_percent = 100 AND (OLD.progress_percent IS NULL OR OLD.progress_percent < 100) THEN
    -- Update completed timestamp
    NEW.completed_at = NOW();
    
    -- Insert certificate if not exists
    INSERT INTO public.certificates (user_id, course_id, certificate_url)
    VALUES (
      NEW.user_id,
      NEW.course_id,
      'https://certificates.learningapp.com/verify/' || NEW.user_id || '/' || NEW.course_id
    ) ON CONFLICT ON CONSTRAINT unique_user_course_certificate DO NOTHING;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_enrollment_completed
  BEFORE UPDATE ON public.enrollments
  FOR EACH ROW EXECUTE FUNCTION public.generate_certificate_on_completion();

-- =====================================================================
-- 3. INDEXES FOR PERFORMANCE OPTIMIZATION
-- =====================================================================

CREATE INDEX idx_courses_category ON public.courses(category_id);
CREATE INDEX idx_courses_instructor ON public.courses(instructor_id);
CREATE INDEX idx_lessons_course_order ON public.lessons(course_id, order_index);
CREATE INDEX idx_quizzes_lesson ON public.quizzes(lesson_id);
CREATE INDEX idx_quiz_attempts_user ON public.quiz_attempts(user_id);
CREATE INDEX idx_quiz_attempts_quiz ON public.quiz_attempts(quiz_id);
CREATE INDEX idx_enrollments_course ON public.enrollments(course_id);
CREATE INDEX idx_certificates_user ON public.certificates(user_id);

-- =====================================================================
-- 4. ROW LEVEL SECURITY (RLS) POLICIES
-- =====================================================================

-- Enable RLS on all tables
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;

-- 4.1 USERS POLICIES
CREATE POLICY "Allow public read access to users profiles" 
  ON public.users FOR SELECT TO authenticated, anon USING (true);

CREATE POLICY "Allow users to update their own profile" 
  ON public.users FOR UPDATE TO authenticated USING (auth.uid() = id);

-- 4.2 CATEGORIES POLICIES
CREATE POLICY "Allow public read access to categories" 
  ON public.categories FOR SELECT TO authenticated, anon USING (true);

CREATE POLICY "Allow admins to manage categories" 
  ON public.categories FOR ALL TO authenticated 
  USING (EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin'));

-- 4.3 COURSES POLICIES
CREATE POLICY "Allow public read access to courses" 
  ON public.courses FOR SELECT TO authenticated, anon USING (true);

CREATE POLICY "Allow instructors/admins to create courses" 
  ON public.courses FOR INSERT TO authenticated 
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role IN ('instructor', 'admin')) 
    AND instructor_id = auth.uid()
  );

CREATE POLICY "Allow instructors/admins to update their courses" 
  ON public.courses FOR UPDATE TO authenticated 
  USING (
    instructor_id = auth.uid() 
    OR EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
  );

CREATE POLICY "Allow instructors/admins to delete their courses" 
  ON public.courses FOR DELETE TO authenticated 
  USING (
    instructor_id = auth.uid() 
    OR EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
  );

-- 4.4 LESSONS POLICIES
CREATE POLICY "Allow enrolled students and instructors to view lessons" 
  ON public.lessons FOR SELECT TO authenticated 
  USING (
    EXISTS (
      SELECT 1 FROM public.enrollments e 
      WHERE e.course_id = lessons.course_id AND e.user_id = auth.uid()
    ) OR EXISTS (
      SELECT 1 FROM public.courses c 
      WHERE c.id = lessons.course_id AND (c.instructor_id = auth.uid() OR EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin'))
    )
  );

CREATE POLICY "Allow instructors and admins to manage lessons" 
  ON public.lessons FOR ALL TO authenticated 
  USING (
    EXISTS (
      SELECT 1 FROM public.courses c 
      WHERE c.id = lessons.course_id AND (c.instructor_id = auth.uid() OR EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin'))
    )
  );

-- 4.5 ENROLLMENTS POLICIES
CREATE POLICY "Allow enrolled students, course instructors and admins to view enrollment" 
  ON public.enrollments FOR SELECT TO authenticated 
  USING (
    user_id = auth.uid() 
    OR EXISTS (SELECT 1 FROM public.courses c WHERE c.id = enrollments.course_id AND c.instructor_id = auth.uid())
    OR EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
  );

CREATE POLICY "Allow students to enroll themselves" 
  ON public.enrollments FOR INSERT TO authenticated 
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "Allow students/admins to update enrollment progress" 
  ON public.enrollments FOR UPDATE TO authenticated 
  USING (
    user_id = auth.uid() 
    OR EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
  );

-- 4.6 QUIZZES POLICIES
CREATE POLICY "Allow enrolled students and instructors to view quizzes" 
  ON public.quizzes FOR SELECT TO authenticated 
  USING (
    EXISTS (
      SELECT 1 FROM public.lessons l
      JOIN public.enrollments e ON e.course_id = l.course_id
      WHERE l.id = quizzes.lesson_id AND e.user_id = auth.uid()
    ) OR EXISTS (
      SELECT 1 FROM public.lessons l
      JOIN public.courses c ON c.id = l.course_id
      WHERE l.id = quizzes.lesson_id AND (c.instructor_id = auth.uid() OR EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin'))
    )
  );

CREATE POLICY "Allow instructors and admins to manage quizzes" 
  ON public.quizzes FOR ALL TO authenticated 
  USING (
    EXISTS (
      SELECT 1 FROM public.lessons l
      JOIN public.courses c ON c.id = l.course_id
      WHERE l.id = quizzes.lesson_id AND (c.instructor_id = auth.uid() OR EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin'))
    )
  );

-- 4.7 QUIZ ATTEMPTS POLICIES
CREATE POLICY "Allow users to view their own quiz attempts" 
  ON public.quiz_attempts FOR SELECT TO authenticated 
  USING (
    user_id = auth.uid() 
    OR EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
  );

CREATE POLICY "Allow students to submit quiz attempts" 
  ON public.quiz_attempts FOR INSERT TO authenticated 
  WITH CHECK (user_id = auth.uid());

-- 4.8 CERTIFICATES POLICIES
CREATE POLICY "Allow public read access to certificates" 
  ON public.certificates FOR SELECT TO authenticated, anon USING (true);

CREATE POLICY "Allow admin to manage certificates directly" 
  ON public.certificates FOR ALL TO authenticated 
  USING (EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin'));

-- =====================================================================
-- 5. SAMPLE DATA INSERTION
-- =====================================================================

-- 5.1 Insert mock users in auth.users (simulate auth signup)
INSERT INTO auth.users (id, email, raw_user_meta_data)
VALUES 
  ('e1a46cf7-8d00-4b2a-89a1-5d9f00000001', 'admin@edxapp.com', '{"full_name": "Admin System", "role": "admin"}'),
  ('e1a46cf7-8d00-4b2a-89a1-5d9f00000002', 'instructor.tuan@edxapp.com', '{"full_name": "Dr. Nguyễn Minh Tuấn", "role": "instructor", "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb"}'),
  ('e1a46cf7-8d00-4b2a-89a1-5d9f00000003', 'instructor.hoa@edxapp.com', '{"full_name": "Prof. Lê Thị Hoa", "role": "instructor", "avatar_url": "https://images.unsplash.com/photo-1544005313-94ddf0286df2"}'),
  ('e1a46cf7-8d00-4b2a-89a1-5d9f00000004', 'student.an@edxapp.com', '{"full_name": "Trần Văn An", "role": "student"}'),
  ('e1a46cf7-8d00-4b2a-89a1-5d9f00000005', 'student.binh@edxapp.com', '{"full_name": "Phạm Thị Bình", "role": "student"}')
ON CONFLICT (id) DO NOTHING;

-- Note: The trigger 'on_auth_user_created' automatically populated public.users with above users!
-- If trigger is not run in testing envs, manual fallback:
INSERT INTO public.users (id, email, full_name, avatar_url, role)
VALUES
  ('e1a46cf7-8d00-4b2a-89a1-5d9f00000001', 'admin@edxapp.com', 'Admin System', '', 'admin'),
  ('e1a46cf7-8d00-4b2a-89a1-5d9f00000002', 'instructor.tuan@edxapp.com', 'Dr. Nguyễn Minh Tuấn', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb', 'instructor'),
  ('e1a46cf7-8d00-4b2a-89a1-5d9f00000003', 'instructor.hoa@edxapp.com', 'Prof. Lê Thị Hoa', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2', 'instructor'),
  ('e1a46cf7-8d00-4b2a-89a1-5d9f00000004', 'student.an@edxapp.com', 'Trần Văn An', '', 'student'),
  ('e1a46cf7-8d00-4b2a-89a1-5d9f00000005', 'student.binh@edxapp.com', 'Phạm Thị Bình', '', 'student')
ON CONFLICT (id) DO UPDATE SET 
  full_name = EXCLUDED.full_name,
  avatar_url = EXCLUDED.avatar_url,
  role = EXCLUDED.role;

-- 5.2 Categories Data
INSERT INTO public.categories (name, icon, color)
VALUES 
  ('Công nghệ thông tin', 'code-bracket', '#3B82F6'),
  ('Kinh doanh & Khởi nghiệp', 'briefcase', '#10B981'),
  ('Thiết kế đồ họa', 'paint-brush', '#F59E0B'),
  ('Ngoại ngữ', 'language', '#EF4444')
ON CONFLICT (name) DO NOTHING;

-- 5.3 Courses Data
INSERT INTO public.courses (id, title, description, thumbnail, instructor_id, category_id, price, level, duration, rating)
VALUES 
  (
    'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380001', 
    'Lập trình Android với Java (MVVM)', 
    'Khóa học từ cơ bản đến nâng cao về phát triển ứng dụng di động Android dùng Java, cấu trúc MVVM và tích hợp Supabase.', 
    'https://images.unsplash.com/photo-1607799279861-4dd421887fb3', 
    'e1a46cf7-8d00-4b2a-89a1-5d9f00000002', 
    1, 
    299000.00, 
    'intermediate', 
    1200, -- 20 hours
    4.85
  ),
  (
    'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380002', 
    'UI/UX Design chuyên nghiệp', 
    'Làm chủ thiết kế giao diện Figma, nghiên cứu người dùng và tối ưu trải nghiệm thiết kế cho Mobile & Web.', 
    'https://images.unsplash.com/photo-1561070791-26c113006238', 
    'e1a46cf7-8d00-4b2a-89a1-5d9f00000003', 
    3, 
    199000.00, 
    'beginner', 
    900, -- 15 hours
    4.90
  )
ON CONFLICT (id) DO NOTHING;

-- 5.4 Lessons Data
INSERT INTO public.lessons (id, course_id, title, video_url, content, order_index, duration)
VALUES 
  (
    'l0eebc99-9c0b-4ef8-bb6d-6bb9bd380011', 
    'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380001', 
    'Bài 1: Giới thiệu khóa học & Thiết lập môi trường', 
    'https://www.w3schools.com/html/mov_bbb.mp4', 
    'Trong bài học này chúng ta sẽ tải Android Studio, cấu hình JDK và chạy Emulator đầu tiên.', 
    1, 
    15
  ),
  (
    'l0eebc99-9c0b-4ef8-bb6d-6bb9bd380012', 
    'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380001', 
    'Bài 2: Cấu trúc mô hình MVVM trong Android', 
    'https://www.w3schools.com/html/movie.mp4', 
    'Học về luồng dữ liệu một chiều của MVVM, cách tách biệt UI (Activity/Fragment) khỏi Business Logic.', 
    2, 
    25
  ),
  (
    'l0eebc99-9c0b-4ef8-bb6d-6bb9bd380013', 
    'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380002', 
    'Bài 1: Khái niệm UI và UX cơ bản', 
    'https://www.w3schools.com/html/mov_bbb.mp4', 
    'Khác biệt giữa giao diện và trải nghiệm người dùng. Tầm quan trọng của tư duy thiết kế.', 
    1, 
    10
  )
ON CONFLICT (id) DO NOTHING;

-- 5.5 Enrollments Data
-- An và Bình đăng ký khóa Android
INSERT INTO public.enrollments (user_id, course_id, progress_percent)
VALUES 
  ('e1a46cf7-8d00-4b2a-89a1-5d9f00000004', 'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380001', 50),
  ('e1a46cf7-8d00-4b2a-89a1-5d9f00000005', 'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380001', 100) -- Auto triggers certificate!
ON CONFLICT (user_id, course_id) DO NOTHING;

-- 5.6 Quizzes Data
INSERT INTO public.quizzes (id, lesson_id, question, options, correct_answer, explanation)
VALUES 
  (
    'q0eebc99-9c0b-4ef8-bb6d-6bb9bd380021', 
    'l0eebc99-9c0b-4ef8-bb6d-6bb9bd380012', 
    'Trong mô hình MVVM, thành phần nào giữ logic xử lý dữ liệu và kết nối API?', 
    '["View (Activity/Fragment)", "ViewModel", "Model (Repository/Remote API)", "Intent"]'::jsonb, 
    'Model (Repository/Remote API)', 
    'Model chịu trách nhiệm trực tiếp với dữ liệu (lấy từ database cục bộ hoặc API qua repository).'
  )
ON CONFLICT (id) DO NOTHING;

-- 5.7 Quiz Attempts Data
INSERT INTO public.quiz_attempts (user_id, quiz_id, selected_answer, is_correct)
VALUES 
  ('e1a46cf7-8d00-4b2a-89a1-5d9f00000004', 'q0eebc99-9c0b-4ef8-bb6d-6bb9bd380021', 'Model (Repository/Remote API)', true)
ON CONFLICT (id) DO NOTHING;
